export const Users = [
  {
    id: 1,
    profilePicture: "https://source.unsplash.com/400x400/person",
    username: "Safak Kocaoglu",
  },
  {
    id: 2,
    profilePicture: "https://source.unsplash.com/400x400/person",
    username: "Janell Shrum",
  },
  {
    id: 3,
    profilePicture: "https://source.unsplash.com/400x400/person",
    username: "Alex Durden",
  },
  {
    id: 4,
    profilePicture: "https://source.unsplash.com/400x400/person",
    username: "Dora Hawks",
  },
  {
    id: 5,
    profilePicture: "https://source.unsplash.com/400x400/person",
    username: "Thomas Holden",
  },
  {
    id: 6,
    profilePicture: "https://source.unsplash.com/400x400/person",
    username: "Shirley Beauchamp",
  },
  {
    id: 7,
    profilePicture: "https://source.unsplash.com/400x400/person",
    username: "Travis Bennett",
  },
  {
    id: 8,
    profilePicture: "https://source.unsplash.com/400x400/person",
    username: "Kristen Thomas",
  },
  {
    id: 9,
    profilePicture: "https://source.unsplash.com/400x400/person",
    username: "Gary Duty",
  },
  {
    id: 10,
    profilePicture: "https://source.unsplash.com/400x400/person",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "https://source.unsplash.com/400x400/nature",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "https://source.unsplash.com/500x500/water",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "https://source.unsplash.com/600x600/beauty",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "https://source.unsplash.com/600x600/water",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "https://source.unsplash.com/700x700/nature",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "https://source.unsplash.com/600x600/food",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "https://source.unsplash.com/600x600/notebook,paper,pen",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "https://source.unsplash.com/600x600/animal",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "https://source.unsplash.com/600x600/anime",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "https://source.unsplash.com/600x500/nature",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
